---
language: php

php:
  - 5.3
  - 5.4

notifications:
  email: false
  slack:
    secure: j0M/YHcUXUB3WIkGM2zVodP7FePghAJ4WsqsloTHfelGTbO3MNfA7bQy+rqixm3bSd4EoAa5AKt74eyDzORkpovXQX0gcP6HsskSNoRUthP1tNPj0c8/yvpWExOcQQO3l39vAJKpdKGOp/KXraU0j36m9lbte2e+Pyg0kUHKDaA=

install:
  - composer selfupdate
  - composer install --no-interaction

before_script:
  - mkdir -p build/logs
  - mysql -e 'create database `test-jam-generated-feed`;'
  - mysql test-jam-generated-feed < tests/test_data/structure.sql

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
